### ISSUE TITLE
热成像可见光相机外参与内参标定

### ISSUE THREAD

**Issue by zhongyanSun** [Clothooo/lvt2calib#1]
您好，请问在您的工作中两个相机的内参是如何标定的，是用您2018年在ICARCV中two step论文中提到的方法吗？以及如果用张正友平面标定法进行热成像和可见光相机的双目标定时图像的分辨率不同该如何处理？

**Comment by junzhang2016** [comment]
> 您好，请问在您的工作中两个相机的内参是如何标定的，是用您2018年在ICARCV中two step论文中提到的方法吗？以及如果用张正友平面标定法进行热成像和可见光相机的双目标定时图像的分辨率不同该如何处理？

是的，和2018年在ICARCV中two step论文中的方法一样的。  我们的RGB和Thermal相机分辨率也不同。只需要把两个相机分别当做单目相机去做内参标定 即可。

**Comment by zhongyanSun** [comment]
感谢您的回复。还想请问您，相机分辨率不同的话做双目标定是不是需要把可见光相机降到和热成像分辨率一致呢？如果降分辨率的话会影响外参吗？

**Comment by junzhang2016** [comment]
> 感谢您的回复。还想请问您，相机分辨率不同的话做双目标定是不是需要把可见光相机降到和热成像分辨率一致呢？如果降分辨率的话会影响外参吗？

我们内外参都没有做分辨率处理，rgb和thermal就是采用各自的分辨率的。外参也是不需要调整分辨率的，因为4x11非对称圆孔板的44个圆心点，在两个2D图像中检测出来，根据44个圆心点的真实距离尺寸，都是可以通过Homograph矩阵+内参 恢复到3D空间的。

**Comment by Clothooo** [comment]
> 感谢您的回复。还想请问您，相机分辨率不同的话做双目标定是不是需要把可见光相机降到和热成像分辨率一致呢？如果降分辨率的话会影响外参吗？

Answer to Q1：我们的方法不要求分辨率一致
Answer to Q2：理论上降分辨率不会影响外参。实际中分辨率的变化有可能导致标定过程中特征点提取的误差，从而导致标定结果的误差，但这种误差是概率性的，基本可以忽视。

**Comment by gyt290811** [comment]
请问2018年在ICARCV中two step论文中的方法，有开源代码吗

**Comment by junzhang2016** [comment]
> 请问2018年在ICARCV中two step论文中的方法，有开源代码吗

您好，感谢您对我们工作的关注。two step论文中的方法还没有开源。之后的工作有可能会开源two step的，如果有消息我会告知。
