### ISSUE TITLE
Process died on os1_32_pattern

### ISSUE THREAD

**Issue by chandroidx** [Clothooo/lvt2calib#13]
[os1_32/laser_pattern-1] process has died [pid 55937, exit code -11, cmd /home/chandroidx/catkin_ws/devel/lib/lvt2calib/ouster_pattern ~cloud_laser:=/ouster/points __name:=laser_pattern __log:=/home/chandroidx/.ros/log/f296362a-e67b-11ee-80c1-b3f7544c7ef2/os1_32-laser_pattern-1.log].
log file: /home/chandroidx/.ros/log/f296362a-e67b-11ee-80c1-b3f7544c7ef2/os1_32-laser_pattern-1*.log

it seems occurs on 
```c++
// AutoDetectLaser.h
plane_segmentation.segment (*inliers, *coefficients);
```

**Comment by chandroidx** [comment]
And short [bag](https://drive.google.com/file/d/1gZvE--l4bss-XP9sP3eDgDliN8t9xPDN/view?usp=drive_link) here :)

**Comment by Clothooo** [comment]
Hi Yechan, you can update the code to our newest version and try again. I hope there will be no bug for the calibration board detection.
However, I noticed that in your provided bag, there were always no points on the background of the circle holes, as shown in the red circle part of this figure. It will cause the failure of circle detection. You'd better adjust the calibration environment.
![Blank diagram - Page 1](https://github.com/Clothooo/lvt2calib/assets/31653202/7fa78a0d-ab3b-4572-8a04-414ab68fb83d)

**Comment by chandroidx** [comment]
I know that there might be difficulty in recognizing circle over there. 
It's just an error occurring even before recognition begins.

I tried with newest version again. 
Process isn't dead but doesn't recognized calib board 😢
https://drive.google.com/file/d/191Te2BRzdSsVpSGJAPyx8rix8kiHyIiL/view?usp=sharing

**Comment by chandroidx** [comment]
I tried reconfigure, but didn't work

Is there any possible way?

**Comment by Clothooo** [comment]
Hi Yechan, you can try reconfiguring again. Here are the parameters I adjusted and succeeded in board detection.
![Blank diagram - Page 1](https://github.com/Clothooo/lvt2calib/assets/31653202/aa64005a-10ca-4924-8415-611b23eb15bc)

**Comment by chandroidx** [comment]
I'm really appreciate for your effort :)
