### ISSUE TITLE
Additional terminals don't appear on docker

### ISSUE THREAD

**Issue by junji-code** [Clothooo/lvt2calib#16]
Hello, when I run the

```sh
bash start_up.bash
```

command on docker container it doesn't run anything and  gives this output:
![image](https://github.com/Clothooo/lvt2calib/assets/71985188/12dd9702-f7f9-4d31-af12-2a4d1d894166)

Thanks for your work, anyways, learning a lot from it! :)

**Comment by Clothooo** [comment]
Hi Junji, thank you for your feedback. I've updated the Dockerfile and hope this issue will not occur. What's more, please luanch the roscore at your local server before using 'start_up.bash' in the docker container.

**Comment by junji-code** [comment]
Right, this worked fine. Thanks!!
