### ISSUE TITLE
Thank your great work!How to generate the template pcd file of the calibration board? Because I have another board with different size.

### ISSUE THREAD

**Issue by tdcsu** [Clothooo/lvt2calib#18]

**Comment by tdcsu** [comment]
Could you please realese the code or provide some suggestions on how to generate the pcd template.
BS
Ditian

**Comment by melonedo** [comment]
I made a script to generate a pcd which looks similar to the one in this repo, although I have not tested it:
https://github.com/melonedo/lvt2calib/blob/c45d8e389acfbd796d5f1251dd5e8716d883249e/src/gen_pcd.cpp

**Comment by Clothooo** [comment]
> Could you please realese the code or provide some suggestions on how to generate the pcd template. BS Ditian

Sorry, we haven't developed it now.

**Comment by Clothooo** [comment]
> I made a script to generate a pcd which looks similar to the one in this repo, although I have not tested it: https://github.com/melonedo/lvt2calib/blob/c45d8e389acfbd796d5f1251dd5e8716d883249e/src/gen_pcd.cpp

Thank you for your kind share.

**Comment by tdcsu** [comment]
> > I made a script to generate a pcd which looks similar to the one in this repo, although I have not tested it: https://github.com/melonedo/lvt2calib/blob/c45d8e389acfbd796d5f1251dd5e8716d883249e/src/gen_pcd.cpp
> 
> Thank you for your kind share.
Great! thank for your share!
