### ISSUE TITLE
Parameters used for extrinsic calibration

### ISSUE THREAD

**Issue by TL-4319** [Clothooo/lvt2calib#22]
Thank you for the great work. I have successfully run the calibration process using the provided rosbag. I do have some questions about what the parameters in extrinsic_calib_l2c launch file do and can't find their mentioning in the docs. Specifically, I am trying to understand

- is_auto_mode
- stdout
- is_multi_exp

If I want to perform calibration with multiple target position, the node that perform Feature collection will export only one file with the multiple position, correct? There should be no need to configure the ex_calib process to non-default value to handle such case?

**Comment by Clothooo** [comment]
Well, I can explain these parameters:

- is_auto_mode: This serves as a toggle switch between automatic and manual modes. **Automatic Mode** (’is_auto_mode = true‘): When running the entire calibration process using the one-click startup script ‘start_up.bash’, ’is_auto_mode‘ is set to true. In this mode, the ’ex_calib‘ thread listens for the ’/end_process‘ variable controlled by the ’pattern_collection‘ process. Once ’/end_process‘ becomes ’true‘, it indicates that all prior processes have completed, and the ’ex_calib‘ thread will automatically read the feature points to compute the extrinsic parameters. **Manual Mode** (’is_auto_mode = false‘): If you're starting the calibration directly using the launch file—as you did—’is_auto_mode‘ remains ’false‘ by default. In this mode, the automatic sequence is bypassed, and you can manually control each step of the calibration process.

**Comment by Clothooo** [comment]
- stdout: This variable was initially used during development to control the node's output parameter, specifying whether the thread's output is printed to the terminal (‘screen’) or written to a log file (‘log’). Later on, I habitually set output directly to 'screen', making this variable unnecessary, but it wasn't removed from the code.
- is_multi_exp: This variable was introduced to facilitate quantitative experiments during early development. When set to 'true', and assuming your feature file contains feature points from n different positions, the 'ex_calib' process will iteratively combine and extract feature points from 1 to n positions to compute the extrinsic parameters, displaying the results and errors. This method was used to generate the experimental results shown in Fig. 8 of the paper.

Regardless, these parameters do not affect the algorithm's operation or performance.

**Comment by Clothooo** [comment]
> If I want to perform calibration with multiple target position, the node that perform Feature collection will export only one file with the multiple position, correct? There should be no need to configure the ex_calib process to non-default value to handle such case?

Yes, you don't need to configure it.

**Comment by TL-4319** [comment]
Thank you for the clarification
