### ISSUE TITLE
Camera image format

### ISSUE THREAD

**Issue by TL-4319** [Clothooo/lvt2calib#23]
Other than the RGB image, does LVT2 support monochrome images and 16bit pixel depth as well? I have optical images that are mono8 and thermal images that are mono16. I wonder if they can be supported directly or do I need to somehow convert them to faux rgb3 format?

**Comment by Clothooo** [comment]
From an algorithmic standpoint, there should be no issues. However, at the code level, monochrome images are not supported. Specifically, in 'cam_pattern.cpp' at line 545, the code is designed to read and convert images in 'bgr8' format. If you try to directly read mono images, it may cause errors.

**Comment by Clothooo** [comment]
https://github.com/Clothooo/lvt2calib/blame/8d6d5b76f39ef577a1bcc65e3bf1a220912187eb/src/camera/cam_pattern.cpp#L545

> From an algorithmic standpoint, there should be no issues. However, at the code level, monochrome images are not supported. Specifically, in 'cam_pattern.cpp' at line 545, the code is designed to read and convert images in 'bgr8' format. If you try to directly read mono images, it may cause errors.

**Comment by Clothooo** [comment]
> From an algorithmic standpoint, there should be no issues. However, at the code level, monochrome images are not supported. Specifically, in 'cam_pattern.cpp' at line 545, the code is designed to read and convert images in 'bgr8' format. If you try to directly read mono images, it may cause errors.

https://github.com/Clothooo/lvt2calib/blob/8d6d5b76f39ef577a1bcc65e3bf1a220912187eb/src/camera/cam_pattern.cpp#L545

**Comment by TL-4319** [comment]
Duplicate the image to RGB channels for RGB images
