### ISSUE TITLE
Support for Blickfeld Cube 1 LIDAR

### ISSUE THREAD

**Issue by TL-4319** [Clothooo/lvt2calib#24]
Hi, gain thank you for the great tool. I am beginning to test the tool with my custom sensor suites where I logs everything as raw data and then construct a bag later on. The LIDAR that I have is blickfeld cube which is a MEM scanning mirror. The scanning pattern is repetitive and is typically visualized as shown below

![image](https://github.com/user-attachments/assets/22d30ee4-fc29-4369-80a7-c04566e601cb)

I was able to test my thermal and RGB images with LVT2 tools and is currently struggling with the LIDAR. Below is a visualization of the raw pointcloud and error

[bag file of this dataset](https://alabama.box.com/s/hxb00b1q7k9uctfvx8j7qr2snxt19can)

![image](https://github.com/user-attachments/assets/696de738-baeb-45f2-8b24-ca802720e454)

![image](https://github.com/user-attachments/assets/956a9591-a719-481a-817d-0bfcb0e45588)

The error said that it fails to find match for field 'intensity', does that  mean my point cloud is missing the intensity field? I have confirmed that my files does have intensity. The point field is shown

![image](https://github.com/user-attachments/assets/7227cf0e-a403-4009-9a4f-1a97ff227051)

I would like to get some guidance of how to get the tool to detect the board. I have tried using the robosense_m1 launch file since they are somewhat similar being repetitive scan sparse lidar and I don't have all information on how to convert blickfeld to velodyne type cloud. 

Thank you in advance

**Comment by TL-4319** [comment]
I made some changes to my raw cloud to bag converter. Instead of writing the intensity values as uint32_t based on blickfeld definition, I wrote it as float. The new bag is as follow.

Now I am seeing no error regarding unrecognized field but I just not detecting the board at all
![image](https://github.com/user-attachments/assets/15efe585-001e-417d-95f3-739afb78658c)

My suspicion is that the value of intensity is somehow now set correctly and the intensity filter with bound [0 15] (based on definition in line 82 of  file ```AutoDetectLaser.h```. Based on rviz, my max intensity range is [0 ~4000] which kinda doesn't make sense. I think my understanding of the intensity filter is wrong. Please let me know how I can scale my intensity to not have the entire pointcloud rejected and how to debug this problem. 

Thank you

**Comment by TL-4319** [comment]
I have found a solution for this LIDAR. 

First of all, the Blickfeld coordinate frame is EAST-NORTH-UP when LVT2 is processing LIDAR cloud as NORTH-WEST-UP so my raw-data to bag script needs to convert that accordingly. The intensity also need to be scaled from 4000 by dividing it by 30 and cast as float for LVT2 to read the cloud correctly. 

I then made a separate launch file for the blickfeld cube 1 based on the rs_m1 and change as follow

```
<launch>

    <arg name="ns_" default="blickfeld"/>
    <arg name="use_passthrough_preprocess" default="false"/>
    <arg name="cloud_tp" default="/blickfeld/cloud"/>
    
    <include file="$(find lvt2calib)/launch/lidar/livox_pattern.launch">
        <arg name="ns_" value="$(arg ns_)"/>
        <arg name="use_passthrough_preprocess" value="$(arg use_passthrough_preprocess)"/>
        <arg name="cloud_tp" value="$(arg cloud_tp)"/>
        <arg name="cluster_tole" value="0.1"/>
        <arg name="cluster_size_min" value="0.001"/>
        <arg name="cluster_size_max" value="10.0"/>
        <arg name="i_filter_out_max" value="100"/>
    </include>
</launch>
```

The resulting is now 

[Screencast from 11-22-2024 11:53:41 AM.webm](https://github.com/user-attachments/assets/85f74436-f078-4de5-be3d-720434e19d97)

I will do some more testing before finalizing a pull request

Thank you

**Comment by Clothooo** [comment]
Sorry for the late reply. We haven't tested the Blickfeld Cube 1 LIDAR ourselves, so your results are very valuable and demonstrate the toolbox's compatibility with a wider range of sensors. Thank you for sharing your experience.

Additionally, for normalizing LIDAR intensity values, there’s a function defined in velo_utils.h that you can use. It’s currently commented out, so you can simply uncomment it. 
https://github.com/Clothooo/lvt2calib/blob/8d6d5b76f39ef577a1bcc65e3bf1a220912187eb/include/lvt2calib/velo_utils.h#L131

If you’d like to adjust the intensity filters, please refer to [HELP.md](https://github.com/Clothooo/lvt2calib/blob/ros_noetic/HELP.md).
