### ISSUE TITLE
16线velodyne激光雷达无法检测标定版平面

### ISSUE THREAD

**Issue by zhongyanSun** [Clothooo/lvt2calib#3]
ICP has converged, score is 0.0618294
the mean is 0.156037
the mean is 0.249597
[ INFO] [1695296928.393437322]: The rmse of unknown cloud to template cloud is: 0.193602
[ INFO] [1695296928.393453946]: The rmse of template cloud to unknown cloud is: 0.147167
[ INFO] [1695296928.393462795]: The mean of rmse is: 0.170385
[ INFO] [1695296928.393539736]: Remianing 708 points in cloud
[ WARN] [1695296928.393831620]: Segmentation No.4	spend[0.000000ms]
number of point clouds in the plane: 410
min_to_rm: 0	max_to_rm: 30
size after intensity filter: 59
size of boudary: 57
**[pcl::IterativeClosestPoint::computeTransformation] Not enough correspondences found. Relax your threshold parameters.
[ WARN] [1695296928.402370885]: ICP hasn't converged!**
the mean is 1.7786
the mean is 1.67792
[ INFO] [1695296928.404290810]: The rmse of unknown cloud to template cloud is: 0.409431
[ INFO] [1695296928.404315916]: The rmse of template cloud to unknown cloud is: 0.314987
[ INFO] [1695296928.404328926]: The mean of rmse is: 0.362209
[ INFO] [1695296928.404423313]: Remianing 298 points in cloud
[ WARN] [1695296928.404860121]: PointCloud represneting the Cluster: 2303 data points.
[ WARN] [1695296928.409570158]: Segmentation No.5	spend[4.000000ms]
number of point clouds in the plane: 829
min_to_rm: 0	max_to_rm: 30
size after intensity filter: 764
size of boudary: 318
您好，请问，终端里一直输出上面的内容，在rviz里没有激光点云的标定版平面，终端里也一直没有velo_16的数字累积。我用的是16线的velodyne激光，标定版与您提到的一致。请问该如何解决？如何调整参数？

**Comment by zhongyanSun** [comment]
ICP has converged, score is 0.00902066
the mean is 0.0772869
the mean is 0.122158
[ INFO] [1695298603.061644085]: The rmse of unknown cloud to template cloud is: 0.055203
[ INFO] [1695298603.061657090]: The rmse of template cloud to unknown cloud is: 0.085340
[ INFO] [1695298603.061669426]: The mean of rmse is: 0.070272
[ INFO] [1695298603.061742481]: Remianing 1 points in cloud
[ WARN] [1695298603.061854714]: PointCloud represneting the Cluster: 895 data points.
[ WARN] [1695298603.063329502]: &lt;&lt;&lt;&lt;&lt;&lt; [Laser] Could not estimate a planar model for the given dataset.
[ WARN] [1695298603.063418182]: PointCloud represneting the Cluster: 833 data points.
[ WARN] [1695298603.065246230]: &lt;&lt;&lt;&lt;&lt;&lt; [Laser] Could not estimate a planar model for the given dataset.
[ WARN] [1695298603.065343358]: PointCloud represneting the Cluster: 695 data points.
[ WARN] [1695298603.066876079]: &lt;&lt;&lt;&lt;&lt;&lt; [Laser] Could not estimate a planar model for the given dataset.
[ WARN] [1695298603.090869317]: &lt;&lt;&lt;&lt;&lt;&lt; [velo_16] CANNOT find the calib borad!
算法支持16线的激光吗？录数据的时有什么额外需要注意的吗

**Comment by Clothooo** [comment]
算法支持16线的，但是标定板的摆放距离不宜过远，至少要保证四元孔的每个圆上都有两条扫描线

**Comment by Clothooo** [comment]
> ICP has converged, score is 0.0618294 the mean is 0.156037 the mean is 0.249597 [ INFO] [1695296928.393437322]: The rmse of unknown cloud to template cloud is: 0.193602 [ INFO] [1695296928.393453946]: The rmse of template cloud to unknown cloud is: 0.147167 [ INFO] [1695296928.393462795]: The mean of rmse is: 0.170385 [ INFO] [1695296928.393539736]: Remianing 708 points in cloud [ WARN] [1695296928.393831620]: Segmentation No.4 spend[0.000000ms] number of point clouds in the plane: 410 min_to_rm: 0 max_to_rm: 30 size after intensity filter: 59 size of boudary: 57 **[pcl::IterativeClosestPoint::computeTransformation] Not enough correspondences found. Relax your threshold parameters. [ WARN] [1695296928.402370885]: ICP hasn't converged!** the mean is 1.7786 the mean is 1.67792 [ INFO] [1695296928.404290810]: The rmse of unknown cloud to template cloud is: 0.409431 [ INFO] [1695296928.404315916]: The rmse of template cloud to unknown cloud is: 0.314987 [ INFO] [1695296928.404328926]: The mean of rmse is: 0.362209 [ INFO] [1695296928.404423313]: Remianing 298 points in cloud [ WARN] [1695296928.404860121]: PointCloud represneting the Cluster: 2303 data points. [ WARN] [1695296928.409570158]: Segmentation No.5 spend[4.000000ms] number of point clouds in the plane: 829 min_to_rm: 0 max_to_rm: 30 size after intensity filter: 764 size of boudary: 318 您好，请问，终端里一直输出上面的内容，在rviz里没有激光点云的标定版平面，终端里也一直没有velo_16的数字累积。我用的是16线的velodyne激光，标定版与您提到的一致。请问该如何解决？如何调整参数？

最近代码进行了部分更新，建议pull最新版本，有些问题的解决可以参考README和HELP文档

**Comment by zhongyanSun** [comment]
请问算法支持LIVOX MID-360吗？实验室没有70

**Comment by junzhang2016** [comment]
> 请问算法支持LIVOX MID-360吗？实验室没有70

支持的，只是可能需要调节一些参数。我们的自动检测标定板算法 是比较通用的一套方法。
