### ISSUE TITLE
Is it possible to use other colors than black and white? 

### ISSUE THREAD

**Issue by SuxRumpf** [Clothooo/lvt2calib#4]
I am in a Building where everything is black and white and the program is not able to find the calib board on the image. So best option for me would be red. Is the program able to detect a red board?

**Comment by junzhang2016** [comment]
> I am in a Building where everything is black and white and the program is not able to find the calib board on the image. So best option for me would be red. Is the program able to detect a red board?

Yes, only if there is a contrast between the board and the backgroud, we can detect it from the image, e.g, white board and black background, red board and white background. One example for red board from our dataset:
![image](https://github.com/Clothooo/lvt2calib/assets/16817603/cd690a17-600b-4608-a39d-976b8b99e946)

**Comment by SuxRumpf** [comment]
Do I need to do anything special? I am trying it right now with a red board but it doesnt recognize the board on the image. I also tried
the - - darkBoard parameter. The background is only black and white so there is clearly a huge difference

**Comment by junzhang2016** [comment]
> background

Hi, can you share the image taken by the camera?
