### ISSUE TITLE
关于标定板尺寸问题

### ISSUE THREAD

**Issue by wang6342** [Clothooo/lvt2calib#6]
您好，想请教您几个问题
1.咱们这个标定板长可以用1000毫米吗，其他尺寸不变，我这边担心大一点容易弯曲，我用铝合金板材也比较重。
2.咱们的标定算法适用激光雷达和红外相机的标定吧，我采用红色的标定板可以实现吗，我看之前有人有疑问。

期待您的回复！

**Comment by junzhang2016** [comment]
> 您好，想请教您几个问题 1.咱们这个标定板长可以用1000毫米吗，其他尺寸不变，我这边担心大一点容易弯曲，我用铝合金板材也比较重。 2.咱们的标定算法适用激光雷达和红外相机的标定吧，我采用红色的标定板可以实现吗，我看之前有人有疑问。
> 
> 期待您的回复！


您好，1. 标定板尺寸是可以变的，但是变过后 ，代码里面需要做一些调整，lidar部分template point cloud需要根据实际尺寸变动；camera部分标定板4个圆孔之间的距离如果有变动需要相应的做出改动，如果4个圆孔尺寸不变，则不需要。

2. 是的，我们的算法适用于 不同类型lidar + rgb 相机 + thermal 相机，任何两两之间的外参标定。红色标定板不影响（对于彩色相机，只需要和背景有对比度，能检测出来4个圆即可；对于热感相机，只需要能加热 有对比度 ，能看到4个圆就可以。）

**Comment by wang6342** [comment]
感谢您的回复！还想麻烦请教您几个问题？
1. 我研究了一下代码，如果只调整标定板长宽，是需要更改下面这个参数吗
调整max_size的值
![Screenshot from 2024-01-30 15-04-56](https://github.com/Clothooo/lvt2calib/assets/49356538/0282a4c2-4817-44bf-a236-6d79f78c001c)

![Screenshot from 2024-01-30 15-12-05](https://github.com/Clothooo/lvt2calib/assets/49356538/dda9594e-c9bc-4e12-8f55-016ace0a51be)
2.如果调整中间4个圆的尺寸，或者4个圆距离标定板中心的距离，是调整下面几个参数吗
circle_radius_ 代表圆半径，centroid_dis_min_代表4个圆距离标定板中心的距离吗？
centroid_dis_max_、circle_seg_thre_代表什么哈？
![Screenshot from 2024-01-30 15-06-20](https://github.com/Clothooo/lvt2calib/assets/49356538/a507440b-ee61-4f7e-83b8-9444165cc2c4)
3.我在做自己的数据集的时候，也采用把多个位置的姿态分多个bag，还是可以采用1个bag去采集，您当时是怎么考虑这个问题的

**Comment by Clothooo** [comment]
关于1：标定板的长宽改动不需要在代码和参数里调整，只要求您依照新的尺寸生成一个模板点云代替原有的four_circle_boundary.pcd模板。如有需要，近期我会增加一个快速生成相应尺寸模板点云的功能。
关于2：标定板圆孔尺寸相关的参数可以直接在rqt_reconfiguration里面调整，或者在lidar_pattern_param文件中修改，不需要改动代码。
  参数解释如下：
  - circle_radius：目标圆形的半径（依据标定板尺寸参数设置）
  - circle_seg_thre：与模型圆形的距离阈值（视噪声而定）
  - centroid_dis_min & centroid_dis_max：检测到的圆形的圆心，与点云质心的距离范围（依据标定板尺寸参数设置）
  今日会在HELP.md中更新所有的参数说明
关于3：我们当时是每个姿态一个bag，这样标定和回播会更方便。

**Comment by wang6342** [comment]
> 关于1：标定板的长宽改动不需要在代码和参数里调整，只要求您依照新的尺寸生成一个模板点云代替原有的four_circle_boundary.pcd模板。如有需要，近期我会增加一个快速生成相应尺寸模板点云的功能。 关于2：标定板圆孔尺寸相关的参数可以直接在rqt_reconfiguration里面调整，或者在lidar_pattern_param文件中修改，不需要改动代码。 参数解释如下：
> 
> * circle_radius：目标圆形的半径（依据标定板尺寸参数设置）
> * circle_seg_thre：与模型圆形的距离阈值（视噪声而定）
> * centroid_dis_min & centroid_dis_max：检测到的圆形的圆心，与点云质心的距离范围（依据标定板尺寸参数设置）
>   今日会在HELP.md中更新所有的参数说明
>   关于3：我们当时是每个姿态一个bag，这样标定和回播会更方便。

感谢您的回复！
方便的话，增加一个快速生成相应尺寸模板点云的功能吧，感谢。
