### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by junji-code** [Clothooo/lvt2calib#7]
Sorry if this is a dumb question, but how can I give my data as input for your LiDAR-LiDAR calibration code? I'm running your code using docker, with the "pull_run.sh" script and have a os1-32 sensor.

**Comment by Clothooo** [comment]
You can just follow 3.1.2 of the Step3 in README. Input you point cloud topic of LiDAR NO.1, namespace of LiDAR NO.1 and these of LiDAR NO.2, following hints of the bash script.

**Comment by junji-code** [comment]
Right, this helped, but I still have some doubts. I see that the data you gave as example on this repo are some ros bags and I could use it. But what is the content of the messages you recorded on them?

Like, is it only the point cloud points? If so, which format do you expect? PCL PointClouds I guess, but with XYZ, XYZ and Intensity, timestamps? How is that data structured?

Thanks a lot in advance.

**Comment by Clothooo** [comment]
[ros_bag](https://wiki.ros.org/rosbag/Commandline) and [ros_topic](https://wiki.ros.org/rostopic?distro=noetic#rostopic_command-line_tool) related tools can help you.

**Comment by junji-code** [comment]
Yes, already saw those, but which information is really needed? There's "t", "reflectivity", "ring", "ambient" and "range", "x", "y", "z", "intensity". From what I saw in your paper i thought only x, y, z and intensity would be used, but now I'm confused, will it work with publishing only x, y, z and intensity?

**Comment by Clothooo** [comment]
For repetitive scanning LiDAR, you need to publish 'ring', which is indeed.
