### ISSUE TITLE
It seems board is not recognized from the Lidar's side

### ISSUE THREAD

**Issue by chandroidx** [Clothooo/lvt2calib#8]
I'm using ouster os1_32 for calibration.

board isn't recognized on the side of lidar, but front and back working.

How can I fix it?

**Comment by Clothooo** [comment]
Did you use our demo rosbag? Could you provide me more info to solve your issue?

**Comment by chandroidx** [comment]
I used my own data.

![image](https://github.com/Clothooo/lvt2calib/assets/58277725/ea93a920-fb34-4a4c-ab87-90a415f8a0e4)

it seems the point clouds on both sides are not processed .

it works on green(O) side,
but not on red(X) side.

**Comment by chandroidx** [comment]
Maybe affected by remove_x_min and remove_x_max
How can I adjust these values?
Or something another way?

**Comment by Clothooo** [comment]
Yes, you can adjust these. Info of these parameters can be seen in HELP.md.

**Comment by Clothooo** [comment]
> I used my own data.
> 
> ![image](https://private-user-images.githubusercontent.com/58277725/307989370-ea93a920-fb34-4a4c-ab87-90a415f8a0e4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjQ4ODQsIm5iZiI6MTcwOTI2NDU4NCwicGF0aCI6Ii81ODI3NzcyNS8zMDc5ODkzNzAtZWE5M2E5MjAtZmIzNC00YTRjLWFiODctOTBhNDE1ZjhhMGU0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwMzQzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWNlMTdlNTgzMTkxY2UxYTJiZDU4YmZkN2U0N2QwMmZmN2VkOWM5MDcxZGIwZTZhZDRhMGEwZDMwZDc4YTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TWbYDyDd-Aywo5SUEqf2gvvfiq-wRCkkZS3HVs_yZhI)
> 
> it seems the point clouds on both sides are not processed .
> 
> it works on green(O) side, but not on red(X) side.

We didn't test the application for such a situation. Maybe we need to do a experiment. Or would you mind sharing your data rosbag to us?
