### ISSUE TITLE
关于调节cluster_size_min

### ISSUE THREAD

**Issue by wang6342** [Clothooo/lvt2calib#9]
您好
      想请教个问题，我测试了livox avia+红外相机，参数设置没有问题。当我采用mid70时候，发现rviz无法显示4个圆点云，终端也显示无法检测到标定板子。
      1. 根据您help里面介绍的方法，更改了i_filter_out_max参数5 10 20 30 40...100不起作用。
      2. 将cluster_size_min从0.05改为0.04点云出现了，等了1，2分钟开始收集，但是激光雷达数据收集终端到60帧不停止，一直在收集，这个调参数有什么需要注意的，Recommend cluster_size_max as 2~5 and match the value of cluster_tole.看还需要兼顾cluster_tole，看代码里面cluster_size_max设置的是20。
      3. 刚准备向您请教，然后我在突然改了上述参数，马上开始收集就可以到60帧停止了。
      4. 还有上次关于4圆孔点云模板的问题，我自己用cloudcompare剪裁了一个模板，您这个模板有坐标系要求吗
      
![Screenshot from 2024-02-27 16-54-53](https://github.com/Clothooo/lvt2calib/assets/49356538/527be2fc-dfb5-4892-bbc3-17ee7de22129)

      
![Screenshot from 2024-02-23 15-20-34](https://github.com/Clothooo/lvt2calib/assets/49356538/2bd686fd-dfaa-4cec-a79c-c42ca75975a3)
![Screenshot from 2024-02-27 17-02-26](https://github.com/Clothooo/lvt2calib/assets/49356538/a45ccdb1-c241-4c5d-9bb8-1ad95dc38b56)

**Comment by Clothooo** [comment]
您这种情况我们也暂时没有碰到过，如果不介意的话可以麻烦分享一下您出现这种情况的rosbag吗？
回答2：cluster_size_min和cluster_size_max都是倍率，用于限制点云聚类结果的size大小，加快聚类速度的。点云密度较大的情况下会推荐将两个值都调大，反之调小。livox mid-70的单帧点云密度较小，可以将cluster_size_min调小。如果希望避免漏掉标定板点云，可以将两值的间隔扩大，代码中cluster_size_max设置为20就是此目的。
回答4：推荐将模板点云旋转到xy平面上，z值都为0

**Comment by wang6342** [comment]
> 您这种情况我们也暂时没有碰到过，如果不介意的话可以麻烦分享一下您出现这种情况的rosbag吗？ 回答2：cluster_size_min和cluster_size_max都是倍率，用于限制点云聚类结果的size大小，加快聚类速度的。点云密度较大的情况下会推荐将两个值都调大，反之调小。livox mid-70的单帧点云密度较小，可以将cluster_size_min调小。如果希望避免漏掉标定板点云，可以将两值的间隔扩大，代码中cluster_size_max设置为20就是此目的。 回答4：推荐将模板点云旋转到xy平面上，z值都为0

感谢指导！
1.我把我的数据传到下面了，我用的是1000*800mm的pcd模板，其他尺寸都不变，用的是mid70和红外热成像相机，相机参数也在解压包里面。情况复现，启动程序和bag后，将cluster_size_min参数改为0.01～0.04出现点云，程序运行3～5分钟左右，就会出现上述到60帧不停止的情况。如果修改参数后输入“Y”马上采集数据，就没有问题。
2.方便的话帮忙看看我自己剪裁的点云模板有问题吗。
https://pan.baidu.com/s/19nI4rkrT3-kQ_B8nFJ3uKQ?pwd=ieh9 提取码: ieh9

**Comment by Clothooo** [comment]
您好，我已经测试过您提供的数据：
1. 您裁剪的点云模板是没有问题的
2. 关于为什么需要将cluster_size_min调整至0.01~0.04才能成功检测。您使用的livox mid70的点云数据为50hz，出现了明显的频闪，每一帧的点云过于稀疏，而我们默认设置的累积10帧原始点云再用来检测是基于10hz的测试数据上的。有三种方法解决该现象：a) 减小lidar数据的输出频率；b) 调整point_cloud_accumualtion节点的acc_num参数至50；c) 减小cluster_size_min
3. 我们这边没有成功复现出lidar特征点采集到的60帧不停止的情况

**Comment by wang6342** [comment]
> 您好，我已经测试过您提供的数据：
> 
> 1. 您裁剪的点云模板是没有问题的
> 2. 关于为什么需要将cluster_size_min调整至0.01~0.04才能成功检测。您使用的livox mid70的点云数据为50hz，出现了明显的频闪，每一帧的点云过于稀疏，而我们默认设置的累积10帧原始点云再用来检测是基于10hz的测试数据上的。有三种方法解决该现象：a) 减小lidar数据的输出频率；b) 调整point_cloud_accumualtion节点的acc_num参数至50；c) 减小cluster_size_min
> 3. 我们这边没有成功复现出lidar特征点采集到的60帧不停止的情况

谢谢回复！
关于2，我们是当时用livox avia检测不到点云，当时考虑是不是聚类速度不够快，当时把10Hz改为50Hz，正确出现了点云，现在根据您的分析，明白啦，谢谢。
